using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OKmzdy.Schema.Database
{
    public class OKmzdySchemaInfo : BaseSchemaInfo
    {
        public OKmzdySchemaInfo(string lpszOwnerName, string lpszUsersName) : base(lpszOwnerName, lpszUsersName)
        {
        }

        public override IDictionary<string, TableDefInfo> CreateTableDictionary()
        {
            return new Dictionary<string, TableDefInfo>()
            {
                { TableStavDatabazeInfo.GetNameKey(), TableStavDatabazeInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableFirmaInfo.GetNameKey(), TableFirmaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSvatekInfo.GetNameKey(), TableSvatekInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableAdresaInfo.GetNameKey(), TableAdresaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableBankSpojInfo.GetNameKey(), TableBankSpojInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableOrganizaceInfo.GetNameKey(), TableOrganizaceInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUtvarInfo.GetNameKey(), TableUtvarInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableDivizeStredInfo.GetNameKey(), TableDivizeStredInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStredCinzakInfo.GetNameKey(), TableStredCinzakInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStredRozpocetInfo.GetNameKey(), TableStredRozpocetInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavSemaforInfo.GetNameKey(), TableStavSemaforInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUzivatelInfo.GetNameKey(), TableUzivatelInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracVyberAggrInfo.GetNameKey(), TablePracVyberAggrInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracInfo.GetNameKey(), TablePracInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableOsdataInfo.GetNameKey(), TableOsdataInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePojistitelInfo.GetNameKey(), TablePojistitelInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableHlaseniZpInfo.GetNameKey(), TableHlaseniZpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracNepritInfo.GetNameKey(), TablePracNepritInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableDanInfo.GetNameKey(), TableDanInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSrazkaInfo.GetNameKey(), TableSrazkaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerInfo.GetNameKey(), TablePpomerInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerDovInfo.GetNameKey(), TablePpomerDovInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerDovRokInfo.GetNameKey(), TablePpomerDovRokInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerMesInfo.GetNameKey(), TablePpomerMesInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerSumInfo.GetNameKey(), TablePpomerSumInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerOzpInfo.GetNameKey(), TablePpomerOzpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerPraxeInfo.GetNameKey(), TablePpomerPraxeInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomerSluzbaInfo.GetNameKey(), TablePpomerSluzbaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracVzdelavaniInfo.GetNameKey(), TablePracVzdelavaniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePrijmySspInfo.GetNameKey(), TablePrijmySspInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePrijmyInfo.GetNameKey(), TablePrijmyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePrijmy1500Info.GetNameKey(), TablePrijmy1500Info.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableProhlaseniInfo.GetNameKey(), TableProhlaseniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableRodinaInfo.GetNameKey(), TableRodinaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePrijmyMesInfo.GetNameKey(), TablePrijmyMesInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableMzdaInfo.GetNameKey(), TableMzdaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableNepritInfo.GetNameKey(), TableNepritInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUvazekInfo.GetNameKey(), TableUvazekInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUzivDataPpomerInfo.GetNameKey(), TableUzivDataPpomerInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUzivReldpDavkaInfo.GetNameKey(), TableUzivReldpDavkaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracReldpDataInfo.GetNameKey(), TablePracReldpDataInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracReldpListekInfo.GetNameKey(), TablePracReldpListekInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracReldp09DataPracInfo.GetNameKey(), TablePracReldp09DataPracInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracReldp09DataPojInfo.GetNameKey(), TablePracReldp09DataPojInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePlatbyKonfigInfo.GetNameKey(), TablePlatbyKonfigInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePlatbyUtvaryInfo.GetNameKey(), TablePlatbyUtvaryInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePopisSlozkaInfo.GetNameKey(), TablePopisSlozkaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePopisSlozkaHInfo.GetNameKey(), TablePopisSlozkaHInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePopisSlozkaTInfo.GetNameKey(), TablePopisSlozkaTInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableTarifniTridaInfo.GetNameKey(), TableTarifniTridaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableTarifniTridaHInfo.GetNameKey(), TableTarifniTridaHInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableTarifniTridaTInfo.GetNameKey(), TableTarifniTridaTInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUcetniOsnovaInfo.GetNameKey(), TableUcetniOsnovaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUcetniPredpisyInfo.GetNameKey(), TableUcetniPredpisyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUcetniPolozkyInfo.GetNameKey(), TableUcetniPolozkyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUzivCiselnikInfo.GetNameKey(), TableUzivCiselnikInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableValutaKurzInfo.GetNameKey(), TableValutaKurzInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableValutaKurzMesInfo.GetNameKey(), TableValutaKurzMesInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZemePlatkoefInfo.GetNameKey(), TableZemePlatkoefInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZemePlatkoefMesInfo.GetNameKey(), TableZemePlatkoefMesInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavKonfigInfo.GetNameKey(), TableStavKonfigInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavKonfigUcertInfo.GetNameKey(), TableStavKonfigUcertInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavKonfigSmtpInfo.GetNameKey(), TableStavKonfigSmtpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavKonfigVrepInfo.GetNameKey(), TableStavKonfigVrepInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavMesInfo.GetNameKey(), TableStavMesInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavMesDanInfo.GetNameKey(), TableStavMesDanInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavStatInfo.GetNameKey(), TableStavStatInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavDefaultInfo.GetNameKey(), TableStavDefaultInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavOzpInfo.GetNameKey(), TableStavOzpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableStavMessageInfo.GetNameKey(), TableStavMessageInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSestavyHtmlInfo.GetNameKey(), TableSestavyHtmlInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePoplatkyInfo.GetNameKey(), TablePoplatkyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableDetailMediaInfo.GetNameKey(), TableDetailMediaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableFiltrMediaInfo.GetNameKey(), TableFiltrMediaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableFiltrPmediaInfo.GetNameKey(), TableFiltrPmediaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableFiltrUmediaInfo.GetNameKey(), TableFiltrUmediaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSestavyFiltrInfo.GetNameKey(), TableSestavyFiltrInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSestavyLstInfo.GetNameKey(), TableSestavyLstInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSestavyUdataInfo.GetNameKey(), TableSestavyUdataInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSestavyUlstInfo.GetNameKey(), TableSestavyUlstInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSestavyUzivInfo.GetNameKey(), TableSestavyUzivInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableSberneMediumInfo.GetNameKey(), TableSberneMediumInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePlatebniMediumInfo.GetNameKey(), TablePlatebniMediumInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableUcetniMediumInfo.GetNameKey(), TableUcetniMediumInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableNavestiFiltrInfo.GetNameKey(), TableNavestiFiltrInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableNavestiUzivInfo.GetNameKey(), TableNavestiUzivInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePracUkazateleInfo.GetNameKey(), TablePracUkazateleInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TablePpomUkazateleInfo.GetNameKey(), TablePpomUkazateleInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableVrepPodaniDataInfo.GetNameKey(), TableVrepPodaniDataInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableExcelUimpInfo.GetNameKey(), TableExcelUimpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImpPnrInfo.GetNameKey(), TableImpPnrInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImpDavkaInfo.GetNameKey(), TableImpDavkaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp01PracInfo.GetNameKey(), TableImp01PracInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp51PracInfo.GetNameKey(), TableImp51PracInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp02ZpVyplatyInfo.GetNameKey(), TableImp02ZpVyplatyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp03OsdataInfo.GetNameKey(), TableImp03OsdataInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp31PrAdresaInfo.GetNameKey(), TableImp31PrAdresaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp05ZdrPojInfo.GetNameKey(), TableImp05ZdrPojInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp06SocPojInfo.GetNameKey(), TableImp06SocPojInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp07PrijmyProhlInfo.GetNameKey(), TableImp07PrijmyProhlInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp08ProhlMesInfo.GetNameKey(), TableImp08ProhlMesInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp09DiteInfo.GetNameKey(), TableImp09DiteInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp17PomerInfo.GetNameKey(), TableImp17PomerInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp18UvazekInfo.GetNameKey(), TableImp18UvazekInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp19MzdaInfo.GetNameKey(), TableImp19MzdaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp20NepritInfo.GetNameKey(), TableImp20NepritInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp21SrazkaInfo.GetNameKey(), TableImp21SrazkaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp101UtvarInfo.GetNameKey(), TableImp101UtvarInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableImp102StrczInfo.GetNameKey(), TableImp102StrczInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestSoczdrPaymsInfo.GetNameKey(), TableZsestSoczdrPaymsInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDanZvyhodneInfo.GetNameKey(), TableZsestDanZvyhodneInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDanOznameniInfo.GetNameKey(), TableZsestDanOznameniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestExtMzdlistInfo.GetNameKey(), TableZsestExtMzdlistInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDanPrijmyInfo.GetNameKey(), TableZsestDanPrijmyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDanPotvrzeniInfo.GetNameKey(), TableZsestDanPotvrzeniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDanPotvr1500Info.GetNameKey(), TableZsestDanPotvr1500Info.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDanHlaseni5478Info.GetNameKey(), TableZsestDanHlaseni5478Info.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDavkaUcetniInfo.GetNameKey(), TableZsestDavkaUcetniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestEldp2004Info.GetNameKey(), TableZsestEldp2004Info.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestMlmesiceInfo.GetNameKey(), TableZsestMlmesiceInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestMlnepritInfo.GetNameKey(), TableZsestMlnepritInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestMlnezdanInfo.GetNameKey(), TableZsestMlnezdanInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestMlpomeryInfo.GetNameKey(), TableZsestMlpomeryInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestMlpracovInfo.GetNameKey(), TableZsestMlpracovInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestNemDavkyInfo.GetNameKey(), TableZsestNemDavkyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPlatbyCrInfo.GetNameKey(), TableZsestPlatbyCrInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPlatbyEuroInfo.GetNameKey(), TableZsestPlatbyEuroInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPrijemSspInfo.GetNameKey(), TableZsestPrijemSspInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestRekapitInfo.GetNameKey(), TableZsestRekapitInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestSocialInfo.GetNameKey(), TableZsestSocialInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDsporHlascaInfo.GetNameKey(), TableZsestDsporHlascaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDsporHlasnaInfo.GetNameKey(), TableZsestDsporHlasnaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDsporVyuctInfo.GetNameKey(), TableZsestDsporVyuctInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotvrzDpInfo.GetNameKey(), TableZsestPotvrzDpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableMzvIisspPredpisyInfo.GetNameKey(), TableMzvIisspPredpisyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestUzivSestInfo.GetNameKey(), TableZsestUzivSestInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestVypDaneInfo.GetNameKey(), TableZsestVypDaneInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestVyplListinyInfo.GetNameKey(), TableZsestVyplListinyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestVyplListkyInfo.GetNameKey(), TableZsestVyplListkyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestVyuctZmenyInfo.GetNameKey(), TableZsestVyuctZmenyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZdravInfo.GetNameKey(), TableZsestZdravInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZmenyZpInfo.GetNameKey(), TableZsestZmenyZpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvd2VetadInfo.GetNameKey(), TableZsestDpzvd2VetadInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvd2VetaoInfo.GetNameKey(), TableZsestDpzvd2VetaoInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvs2VetaoInfo.GetNameKey(), TableZsestDpzvs2VetaoInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvd2VetaeInfo.GetNameKey(), TableZsestDpzvd2VetaeInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvs2VetaeInfo.GetNameKey(), TableZsestDpzvs2VetaeInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvd2VetafInfo.GetNameKey(), TableZsestDpzvd2VetafInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvd2VetagInfo.GetNameKey(), TableZsestDpzvd2VetagInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvd2VetabInfo.GetNameKey(), TableZsestDpzvd2VetabInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestDpzvd2VetacInfo.GetNameKey(), TableZsestDpzvd2VetacInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPpomerPraxeInfo.GetNameKey(), TableZsestPpomerPraxeInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotvrzHlavInfo.GetNameKey(), TableZsestPotvrzHlavInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPot313VedlInfo.GetNameKey(), TableZsestPot313VedlInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPot313NeschInfo.GetNameKey(), TableZsestPot313NeschInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPot313PohlInfo.GetNameKey(), TableZsestPot313PohlInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotvrzZpInfo.GetNameKey(), TableZsestPotvrzZpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotvrzSpInfo.GetNameKey(), TableZsestPotvrzSpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestKontrZdrpInfo.GetNameKey(), TableZsestKontrZdrpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestKontrSocpInfo.GetNameKey(), TableZsestKontrSocpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestOznamSocpInfo.GetNameKey(), TableZsestOznamSocpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPrehlSocpInfo.GetNameKey(), TableZsestPrehlSocpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPrilohaSocpInfo.GetNameKey(), TableZsestPrilohaSocpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestSlevySocpInfo.GetNameKey(), TableZsestSlevySocpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestNemDavky09Info.GetNameKey(), TableZsestNemDavky09Info.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZadNemInfo.GetNameKey(), TableZsestZadNemInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZadNemNeschInfo.GetNameKey(), TableZsestZadNemNeschInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZadNemRozhobdInfo.GetNameKey(), TableZsestZadNemRozhobdInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZadMatInfo.GetNameKey(), TableZsestZadMatInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZadMatNeschInfo.GetNameKey(), TableZsestZadMatNeschInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZadMatRozhobdInfo.GetNameKey(), TableZsestZadMatRozhobdInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotvdavSspInfo.GetNameKey(), TableZsestPotvdavSspInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestReldp09PracInfo.GetNameKey(), TableZsestReldp09PracInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestReldp09PojInfo.GetNameKey(), TableZsestReldp09PojInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPrehvyuctfinInfo.GetNameKey(), TableZsestPrehvyuctfinInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotVptInfo.GetNameKey(), TableZsestPotVptInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotVptRozhobdInfo.GetNameKey(), TableZsestPotVptRozhobdInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPrehlZdrpInfo.GetNameKey(), TableZsestPrehlZdrpInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestZadostBonusmrInfo.GetNameKey(), TableZsestZadostBonusmrInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestPotvvrzOsr111Info.GetNameKey(), TableZsestPotvvrzOsr111Info.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestKartazZaklInfo.GetNameKey(), TableZsestKartazZaklInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestKartazPpozInfo.GetNameKey(), TableZsestKartazPpozInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestKartazVzdvInfo.GetNameKey(), TableZsestKartazVzdvInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { TableZsestKartazPpomInfo.GetNameKey(), TableZsestKartazPpomInfo.GetDictValue(m_strOwnerName, m_strUsersName) },

            };
        }
        public override IDictionary<string, TableDefInfo> CreateSubZTableDictionary()
        {
            return new Dictionary<string, TableDefInfo>()
            {
            };
        }
        public override IDictionary<string, TableDefInfo> CreateSubITableDictionary()
        {
            return new Dictionary<string, TableDefInfo>()
            {
            };
        }
        public override IDictionary<string, TableDefInfo> CreateSubXTableDictionary()
        {
            return new Dictionary<string, TableDefInfo>()
            {
            };
        }
        public override IDictionary<string, QueryDefInfo> CreateQueryDictionary()
        {
            return new Dictionary<string, QueryDefInfo>()
            {
                { QueryKrokujPracPocitanyInfo.GetNameKey(), QueryKrokujPracPocitanyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryKrokujPracovnikyInfo.GetNameKey(), QueryKrokujPracovnikyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracZarazeniInfo.GetNameKey(), QueryVyberPracZarazeniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPPomZarazeniInfo.GetNameKey(), QueryVyberPPomZarazeniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracOpravneniInfo.GetNameKey(), QueryVyberPracOpravneniInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracovnikyFiltrXOInfo.GetNameKey(), QueryVyberPracovnikyFiltrXOInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracovnikyFiltrXPInfo.GetNameKey(), QueryVyberPracovnikyFiltrXPInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracovnikyFiltrXZInfo.GetNameKey(), QueryVyberPracovnikyFiltrXZInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracovnikyFiltrZPInfo.GetNameKey(), QueryVyberPracovnikyFiltrZPInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracPocitanyInfo.GetNameKey(), QueryVyberPracPocitanyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPracovnikyInfo.GetNameKey(), QueryVyberPracovnikyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberUtvaryInfo.GetNameKey(), QueryVyberUtvaryInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberSestavyInfo.GetNameKey(), QueryVyberSestavyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberSbMediaInfo.GetNameKey(), QueryVyberSbMediaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberPlMediaInfo.GetNameKey(), QueryVyberPlMediaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberUcMediaInfo.GetNameKey(), QueryVyberUcMediaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberUcetPrPolozkyInfo.GetNameKey(), QueryVyberUcetPrPolozkyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryHodnExtMListInfo.GetNameKey(), QueryHodnExtMListInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryCelkExtMListInfo.GetNameKey(), QueryCelkExtMListInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryHodnVyuctFinInfo.GetNameKey(), QueryHodnVyuctFinInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryCelkVyuctFinInfo.GetNameKey(), QueryCelkVyuctFinInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QuerySocialInfo.GetNameKey(), QuerySocialInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QuerySumaDanInfo.GetNameKey(), QuerySumaDanInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyplListkySortInfo.GetNameKey(), QueryVyplListkySortInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryMzvIIsspPredpisyInfo.GetNameKey(), QueryMzvIIsspPredpisyInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberReldp09DavkaInfo.GetNameKey(), QueryVyberReldp09DavkaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberReldp09DataInfo.GetNameKey(), QueryVyberReldp09DataInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberReldpDavkaInfo.GetNameKey(), QueryVyberReldpDavkaInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
                { QueryVyberReldpDataInfo.GetNameKey(), QueryVyberReldpDataInfo.GetDictValue(m_strOwnerName, m_strUsersName) },
            };
        }
    }
}